CREATE TABLE ORDERS_PRODUCTS(
    ORDER_ID INT NOT NULL REFERENCES ORDERS(ID),
    PRODUCT_ID INT NOT NULL REFERENCES PRODUCT(ID),
    CONSTRAINT PK_ORDERS_PRODUCTS PRIMARY KEY (ORDER_ID ,PRODUCT_ID ),
    QUANTITY INT NOT NULL
);
